version: '3.8'
services:
  database:
    container_name: postgres
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=currency-converter-db
      - POSTGRES_PORT=5432
    restart: always
  currency-app:
    container_name: currency-converter
    image: 'currency-converter'
    build:
      context: ./Docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/currency-converter-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always